### ISSUE TITLE
how to find the  encrypted app ticket and decryptionKey

### ISSUE THREAD

**Issue by poemplayer** [DoctorMcKay/node-steam-appticket#2]
thanks for your method,but i am a green hand . I don't know how to find the encrypted app ticket and decryptionKey , i will appreciate it 
 if you can give some help .

**Comment by DoctorMcKay** [comment]
Are you the publisher of a game on Steam?

**Comment by poemplayer** [comment]
No,Whether it must be getting from steam SDK?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年11月28日(星期天) 晚上8:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DoctorMcKay/node-steam-appticket] how to find the  encrypted app ticket and decryptionKey (Issue #2)





 
Are you the publisher of a game on Steam?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DoctorMcKay** [comment]
Only the publisher of a game can get the game's decryption key.

**Comment by poemplayer** [comment]
Thanks for your answer .But there are still questions. For example, there is an app&nbsp;DecryptionKey "5c5a37b435d9eef062eaf42d50bc6406d1b5b39b7b0a78023b11b26e02517422" for the game "Orcs Must Die! 3" which appid is "1522820", wheather i can play the game with the above information whithout steam verify and what should I do for this?






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DoctorMcKay/node-steam-appticket"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月28日(星期天) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DoctorMcKay/node-steam-appticket] how to find the  encrypted app ticket and decryptionKey (Issue #2)





 
Only the publisher of a game can get the game's decryption key.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DoctorMcKay** [comment]
That's the key for decrypting the depot's contents. It has nothing to do with encrypted app tickets.

**Comment by poemplayer** [comment]
is there any way to use&nbsp;decryptingket&nbsp;to download the depot




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Alex ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 下午3:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [DoctorMcKay/node-steam-appticket] how to find the  encrypted app ticket and decryptionKey (Issue #2)





 
That's the key for decrypting the depot's contents. It has nothing to do with encrypted app tickets.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
