### ISSUE TITLE
How to convert a ticket from a string to hexadecimal

### ISSUE THREAD

**Issue by hubing123** [DoctorMcKay/node-steam-appticket#3]

**Comment by DoctorMcKay** [comment]
I assume by "string" you mean a binary string?

```js
let binaryString = getBinaryStringSomehow();
let buffer = Buffer.from(binaryString, 'binary');
let hexadecimal = buffer.toString('hex');
```

[Buffer docs](https://nodejs.org/api/buffer.html#static-method-bufferfromstring-encoding)

**Comment by hubing123** [comment]
let binaryString = "261551";
let buffer = Buffer.from(binaryString, 'binary');
let ticket = buffer.toString('hex');
const decryptionKey = '16a71c423df683e98af58e40c60a6fc8087dc360f977a73c7d138e8d26b99062';
console.log(AppTicket.parseEncryptedAppTicket(ticket, decryptionKey));

the output is null, but  the ticket and decryptionKey is right, could you help me?

**Comment by DoctorMcKay** [comment]
"261551" doesn't look like a binary string.
